--PACKAGE 생성(BODY)
CREATE OR REPLACE PACKAGE BODY EMP_MGMT AS 
--급여 조정
    PROCEDURE ADJUST_SAL(V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER) IS 
    BEGIN
     IF V_FLAG = 'INCREASE' THEN
     UPDATE EMP SET SAL = SAL+(SAL * (V_PCT/100))
    WHERE EMPNO = V_EMPNO;
    ELSE 
     UPDATE EMP SET SAL = SAL-(SAL * (V_PCT/100))
     WHERE EMPNO = V_EMPNO;
     END IF; 
    END;
--연봉 계산
    FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER) RETURN NUMBER IS V_SAL NUMBER;
    BEGIN
        SELECT(SAL + NVL(COMM, 0))*12 INTO V_SAL
         FROM EMP
        WHERE EMPNO = V_EMPNO;
        RETURN V_SAL;
    END;
--퇴직 급여 
    FUNCTION GET_RETIRE_MONEY (V_EMPNO NUMBER) RETURN NUMBER IS V_SAL NUMBER;
    BEGIN
        SELECT ROUND((SAL+NVL(COMM,0)) 
                  * ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE),0) / 12, 0)
                  INTO V_SAL
        FROM EMP
        WHERE EMPNO = V_EMPNO;
        RETURN V_SAL;
    END;
--사원정보 삭제 
    PROCEDURE REMOVE_EMP(V_EMPNO NUMBER) IS
    BEGIN
    DELETE FROM EMP
    WHERE EMPNO = V_EMPNO;
    END;
--사원 입사일자 
    FUNCTION GET_HIREDATE(V_EMPNO NUMBER, V_FMT VARCHAR2) RETURN VARCHAR2 IS V_HIREDATE VARCHAR2(20);
    BEGIN
    SELECT TO_CHAR(HIREDATE, V_FMT) INTO V_HIREDATE
     FROM EMP
    WHERE EMPNO = V_EMPNO;
    RETURN V_HIREDATE;
    END;
END;